# Generated by Django 5.1 on 2024-08-21 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=100, unique=True)),
                ('fasta_file', models.FileField(upload_to='proteins/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('selected_as_main_ref', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SAPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_address', models.CharField(max_length=100)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_addresses', to='sapapp.referenceprotein')),
            ],
        ),
    ]
